% -------------------------------------------------------------------
%  Generated by MATLAB on 29-May-2016 15:09:12
%  MATLAB version: 8.5.0.197613 (R2015a)
% -------------------------------------------------------------------
saveVarsMat = load('clutch_init.mat');

be = 2;

bv = 1;

f1 = [1; 6; 11; 16; 21; 26; 31; 36; 41; 46; 51];

Fn = ...
  [0 0;
   1 0.8;
   2 1.6;
   3 1.6;
   4 1.6;
   5 1.6;
   6 0.8;
   7 0;
   8 0;
   9 0;
   10 0];

Ie = 1;

Iv = 5;

muk = 1;

mus = 1.5;

R = 1;

sldemo_clutch_output = saveVarsMat.sldemo_clutch_output; % <1x1 Simulink.SimulationData.Dataset> unsupported class

Tin = ...
  [1 2;
   2 2;
   3 2;
   4 2;
   5 2;
   6 0;
   7 0;
   8 0;
   9 0;
   10 0];

z = 1;

clear saveVarsMat;
